import {expect,it} from 'vitest';
import {assetValue,portfolioHistory,parseAssetValue,validateAssets,type Asset} from './assets';
import {validateBackup,emptyData} from './domain';
const asset:Asset={id:'a',type:'Cuenta',bank:'N26',name:'N26',color:'#174B47',notes:'',valuations:[{date:'2026-09-20',valueCents:10000},{date:'2026-09-22',valueCents:12500}]};
it('preserves dated valuations and carries forward each asset at its recorded dates',()=>{expect(assetValue(asset)).toBe(12500);expect(portfolioHistory([asset,{...asset,id:'b',valuations:[{date:'2026-09-21',valueCents:5000}]}])).toEqual([{date:'2026-09-20',valueCents:10000},{date:'2026-09-21',valueCents:15000},{date:'2026-09-22',valueCents:17500}]);});
it('supports zero and negative balances with exact cents',()=>{expect(parseAssetValue('0')).toBe(0);expect(parseAssetValue('-10,05')).toBe(-1005);expect(()=>parseAssetValue('1.000,01')).toThrow();});
it('migrates old backups and preserves new assets',()=>{expect(validateBackup(JSON.stringify({version:1,transactions:[],accounts:['Efectivo'],budgets:{}})).assets).toEqual([]);const data={...emptyData(),assets:[asset]};expect(validateBackup(JSON.stringify(data))).toEqual(data);});
it('rejects malformed and duplicate valuation data',()=>{expect(()=>validateAssets([{...asset,valuations:[{date:'2026-02-30',valueCents:2}]}])).toThrow();expect(()=>validateAssets([asset,asset])).toThrow();expect(()=>validateAssets([{...asset,color:'red'}])).toThrow();});
import {accountBalance,assetSeries} from './assets';
import type {Transaction} from './domain';
const tr:Asset={id:'tr',type:'Cuenta',bank:'Trade Republic',name:'Trade Republic',color:'#252525',notes:'',valuations:[],openingBalance:{date:'2026-09-01',valueCents:100000}};
const n26:Asset={...tr,id:'n26',bank:'N26',name:'N26',openingBalance:{date:'2026-09-01',valueCents:20000}};
const move=(p:Partial<Transaction>):Transaction=>({id:crypto.randomUUID(),type:'expense',amountCents:100,merchant:'x',bank:'N26',category:'Otros',date:'2026-09-10',source:'import',...p});
it('moves money between own accounts without counting spending',()=>{const list=[move({type:'transfer',amountCents:2000,bank:'Trade Republic',toAccount:'N26',category:'Transferencia'})];expect(accountBalance(tr,list)).toBe(98000);expect(accountBalance(n26,list)).toBe(22000);});
it('applies expenses and incomes from the opening date onwards',()=>{const list=[move({amountCents:500}),move({type:'income',amountCents:300}),move({amountCents:999,date:'2026-08-31'})];expect(accountBalance(n26,list)).toBe(19800);expect(assetSeries(n26,list)).toEqual([{date:'2026-09-01',valueCents:20000},{date:'2026-09-10',valueCents:19800}]);});
it('keeps iban and opening balance through validation',()=>{expect(validateAssets([{...tr,iban:'ES6115860001467451815811'}])[0]).toMatchObject({iban:'ES6115860001467451815811',openingBalance:{date:'2026-09-01',valueCents:100000}});expect(()=>validateAssets([{...tr,iban:'nope'}])).toThrow();});
it('does not deduct expenses pending review or marked as not deducted',()=>{const list=[move({amountCents:500,pending:true}),move({amountCents:300,skipBalance:true}),move({amountCents:100})];expect(accountBalance(n26,list)).toBe(19900);});
it('moves an investment contribution from cash into an asset without changing total wealth',()=>{
 const fund:Asset={id:'fund',type:'Inversión',bank:'Trade Republic',name:'Fondo indexado',color:'#252525',notes:'',valuations:[{date:'2026-09-01',valueCents:0}]};
 const contribution=move({type:'transfer',amountCents:10000,bank:'Trade Republic',toAccount:fund.name,category:'Transferencia',source:'manual',investmentAssetId:fund.id});
 expect(accountBalance(tr,[contribution])).toBe(90000);
 expect(accountBalance(fund,[contribution])).toBe(10000);
 expect(accountBalance(tr,[contribution])+accountBalance(fund,[contribution])).toBe(100000);
});
it('does not count a contribution twice after an updated investment valuation',()=>{
 const first=move({id:'first',type:'transfer',amountCents:10000,bank:'Trade Republic',toAccount:'Fondo indexado',category:'Transferencia',source:'manual',investmentAssetId:'fund'});
 const second=move({id:'second',type:'transfer',amountCents:5000,bank:'Trade Republic',toAccount:'Fondo indexado',category:'Transferencia',source:'manual',investmentAssetId:'fund'});
 const fund:Asset={id:'fund',type:'Inversión',bank:'Trade Republic',name:'Fondo indexado',color:'#252525',notes:'',valuations:[{date:'2026-09-11',valueCents:12000,includedInvestmentIds:['first']}]};
 expect(accountBalance(fund,[first,second])).toBe(17000);
 expect(accountBalance(fund,[first])).toBe(12000);
 expect(validateBackup(JSON.stringify({...emptyData(),transactions:[first],assets:[fund]})).assets).toEqual([fund]);
 expect(()=>validateBackup(JSON.stringify({...emptyData(),transactions:[first],assets:[]}))).toThrow();
});
