import {type Asset,validateAssets} from './assets';
export type Transaction={id:string;type:'expense'|'income'|'transfer';amountCents:number;merchant:string;bank:string;toAccount?:string;category:string;date:string;source:'manual'|'shortcut'|'demo'|'import';externalId?:string;pairedExternalId?:string};
export type Category={name:string;color:string};
export type Profile={displayName:string;ownerName:string;avatar?:string};
export type Data={version:2;transactions:Transaction[];accounts:string[];budgets:Record<string,number>;assets?:Asset[];categories:Category[];profile:Profile};
export const categories=['Alimentación','Transporte','Ocio','Hogar','Salud','Compras','Restauración','Suscripciones','Otros'];
export const colors=['#7c3aed','#0ea5a4','#6366f1','#ca8a04','#e0527d','#a855f7','#059669','#3b82f6','#9ca3af'];
export const TRANSFER='Transferencia';
export const defaultCategories=():Category[]=>categories.map((name,i)=>({name,color:colors[i%colors.length]}));
export const emptyProfile=():Profile=>({displayName:'',ownerName:''});
export const money=(cents:number)=>new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR'}).format(cents/100);
export const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
export function parseMoney(value:string){if(!/^\d{1,6}([.,]\d{1,2})?$/.test(value.trim()))throw Error('Escribe un importe válido, sin separadores de miles y con hasta dos decimales.');const [whole,decimal='']=value.trim().replace(',','.').split('.');const cents=Number(whole)*100+Number(decimal.padEnd(2,'0'));if(cents<=0||cents>99999999)throw Error('El importe debe estar entre 0,01 y 999.999,99 €.');return cents;}
export const emptyData=():Data=>({version:2,transactions:[],accounts:['Efectivo'],budgets:{},assets:[],categories:defaultCategories(),profile:emptyProfile()});
export function validDate(date:string){return /^\d{4}-\d{2}-\d{2}$/.test(date)&&!isNaN(Date.parse(date))&&new Date(date+'T12:00:00Z').toISOString().slice(0,10)===date;}
const text=(value:unknown)=>typeof value==='string'&&value.trim().length>0&&value.length<=200;
export function validTransaction(t:any):t is Transaction{return t&&text(t.id)&&['expense','income','transfer'].includes(t.type)&&Number.isSafeInteger(t.amountCents)&&t.amountCents>0&&t.amountCents<=99999999&&text(t.merchant)&&text(t.bank)&&text(t.category)&&typeof t.date==='string'&&validDate(t.date)&&['manual','shortcut','demo','import'].includes(t.source)&&(t.externalId===undefined||text(t.externalId))&&(t.pairedExternalId===undefined||text(t.pairedExternalId))&&(t.type==='transfer'?text(t.toAccount)&&t.toAccount!==t.bank:t.toAccount===undefined);}
export function validateBackup(raw:string):Data{const value=JSON.parse(raw);if(![1,2].includes(value.version)||!Array.isArray(value.transactions)||!value.transactions.every(validTransaction)||new Set(value.transactions.map((t:Transaction)=>t.id)).size!==value.transactions.length||!Array.isArray(value.accounts)||!value.accounts.length||!value.accounts.every(text)||!value.budgets||Array.isArray(value.budgets)||typeof value.budgets!=='object'||!Object.entries(value.budgets).every(([month,amount])=>/^\d{4}-(0[1-9]|1[0-2])$/.test(month)&&Number.isSafeInteger(amount)&&Number(amount)>0))throw Error('Copia no válida. Revisa versión, fechas, importes y cuentas.');
 const cats=value.categories??defaultCategories(),profile=value.profile??emptyProfile();
 if(!Array.isArray(cats)||!cats.length||!cats.every((c:any)=>c&&text(c.name)&&c.name.length<=40&&typeof c.color==='string'&&/^#[0-9a-f]{6}$/i.test(c.color))||new Set(cats.map((c:any)=>c.name.toLowerCase())).size!==cats.length)throw Error('Categorías no válidas en la copia.');
 if(!profile||typeof profile.displayName!=='string'||profile.displayName.length>100||typeof profile.ownerName!=='string'||profile.ownerName.length>200||(profile.avatar!==undefined&&(typeof profile.avatar!=='string'||!profile.avatar.startsWith('data:image/')||profile.avatar.length>400000)))throw Error('Perfil no válido en la copia.');
 return {version:2,transactions:value.transactions.map((t:Transaction)=>({id:t.id,type:t.type,amountCents:t.amountCents,merchant:t.merchant,bank:t.bank,...(t.toAccount?{toAccount:t.toAccount}:{}),category:t.category,date:t.date,source:t.source,...(t.externalId?{externalId:t.externalId}:{}),...(t.pairedExternalId?{pairedExternalId:t.pairedExternalId}:{})})),accounts:value.accounts,budgets:value.budgets,assets:validateAssets(value.assets),categories:cats.map((c:any)=>({name:c.name,color:c.color})),profile:{displayName:profile.displayName,ownerName:profile.ownerName,...(profile.avatar?{avatar:profile.avatar}:{})}};}
export function mergeTransactions(local:Transaction[],remote:Transaction[]){if(!remote.every(validTransaction))throw Error('El receptor devolvió movimientos no válidos.');const out=[...local];const ids=new Set(local.map(t=>t.id));const events=new Set(local.flatMap(t=>t.externalId?[t.externalId]:[]));for(const t of remote){if(ids.has(t.id)||(t.externalId&&events.has(t.externalId)))continue;out.push(t);ids.add(t.id);if(t.externalId)events.add(t.externalId);}return out;}
export function shiftMonth(month:string,delta:number){const [year,m]=month.split('-').map(Number);const d=new Date(year,m-1+delta,1);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;}
export function summary(items:Transaction[],month:string){const current=items.filter(t=>t.date.startsWith(month));const expenses=current.filter(t=>t.type==='expense');const sum=(list:Transaction[])=>list.reduce((a,t)=>a+t.amountCents,0);const expense=sum(expenses);const income=sum(current.filter(t=>t.type==='income'));const previous=sum(items.filter(t=>t.type==='expense'&&t.date.startsWith(shiftMonth(month,-1))));const grouped=Object.entries(expenses.reduce<Record<string,number>>((a,t)=>{a[t.category]=(a[t.category]||0)+t.amountCents;return a;},Object.create(null))).sort((a,b)=>b[1]-a[1]);return {expense,income,previous,change:previous?(expense-previous)/previous*100:null,grouped,expenses,current};}
export function download(name:string,value:unknown){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function demoData():Transaction[]{return [{merchant:'Mercado de ejemplo',category:'Alimentación',amountCents:4250},{merchant:'Suscripción demo',category:'Suscripciones',amountCents:1299},{merchant:'Café de ejemplo',category:'Restauración',amountCents:350},{merchant:'Transporte demo',category:'Transporte',amountCents:2100},{merchant:'Librería de ejemplo',category:'Compras',amountCents:2490}].map((t,i)=>({...t,id:crypto.randomUUID(),date:today().slice(0,8)+String(Math.max(1,new Date().getDate()-i)).padStart(2,'0'),type:'expense',bank:'Efectivo',source:'demo'}));}
