import {useState} from 'react';
import {ArrowLeft,Upload,Check} from 'lucide-react';
import {type Data,money,validDate,today} from './domain';
import {type Asset,banks,parseAssetValue,cashTypes} from './assets';
import {readStatement} from './import/detect';
import type {ParsedStatement} from './import/common';
import {guessMapping,parseGenericCsv,type CsvMapping} from './import/genericCsv';
import {buildReview,applyReview,type ReviewRow} from './import/review';
import {EXTERNAL} from './import/classify';
import './settings.css';
import './import.css';
const STATUS:Record<ReviewRow['status'],string>={new:'Nuevo',duplicate:'Ya importado',own:'Transferencia propia',maybe:'¿Transferencia propia?',paired:'Ya registrada en la otra cuenta'};
type Step='owner'|'file'|'map'|'account'|'review'|'done';
export default function ImportFlow({data,onSave,onBack}:{data:Data;onSave:(d:Data)=>void;onBack:()=>void}){
 const [step,setStep]=useState<Step>(data.profile.ownerName?'file':'owner'),[owner,setOwner]=useState(data.profile.ownerName),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const [csv,setCsv]=useState<string[][]>([]),[mapping,setMapping]=useState<CsvMapping>({date:-1,description:-1,amount:-1}),[csvBank,setCsvBank]=useState('');
 const [statement,setStatement]=useState<ParsedStatement|null>(null),[account,setAccount]=useState(''),[opening,setOpening]=useState({date:'',value:''}),[draft,setDraft]=useState<Data>(data),[rows,setRows]=useState<ReviewRow[]>([]),[result,setResult]=useState('');
 const assets=data.assets??[],cash=assets.filter(a=>cashTypes.includes(a.type)),names=Array.from(new Set([...cash.map(a=>a.name),...data.accounts]));
 const fail=(e:unknown)=>setError((e as Error).message);
 function chooseStatement(st:ParsedStatement){setStatement(st);const match=cash.find(a=>st.ownIban&&a.iban===st.ownIban)??cash.find(a=>a.bank===st.bankName||a.name===st.bankName);setAccount(match?.name??'__new');setOpening({date:st.opening?.date??[...st.rows].sort((a,b)=>a.date.localeCompare(b.date))[0]?.date??today(),value:st.opening?String(st.opening.valueCents/100).replace('.',','):''});setStep('account');}
 async function pick(file?:File){if(!file)return;setBusy(true);setError('');try{const d=await readStatement(file);if(d.kind==='statement')chooseStatement(d.statement);else{setCsv(d.rows);setMapping(guessMapping(d.rows[0]));setCsvBank(file.name.replace(/\.[^.]+$/,''));setStep('map');}}catch(e){fail(e);}finally{setBusy(false);}}
 const current=assets.find(a=>a.name===account),needsOpening=account==='__new'||(!!current&&!current.openingBalance);
 function toReview(){try{if(!statement)return;let next=data,name=account;
  if(account==='__new'||(current&&!current.openingBalance&&opening.value.trim())){if(!validDate(opening.date))throw Error('Elige la fecha del saldo inicial.');const valueCents=parseAssetValue(opening.value||'0');
   if(account==='__new'){name=names.includes(statement.bankName)?`${statement.bankName} ${cash.length+1}`:statement.bankName;const asset:Asset={id:crypto.randomUUID(),type:'Cuenta',bank:statement.bankName,name,color:banks.find(b=>b.name===statement.bankName)?.color??'#5b21b6',notes:'',valuations:[],openingBalance:{date:opening.date,valueCents},...(statement.ownIban?{iban:statement.ownIban}:{})};next={...data,assets:[...assets,asset],accounts:Array.from(new Set([...data.accounts,name]))};}
   else next={...data,assets:assets.map(a=>a.id===current!.id?{...a,openingBalance:{date:opening.date,valueCents},...(statement.ownIban&&!a.iban?{iban:statement.ownIban}:{})}:a)};}
  if(!name)throw Error('Elige la cuenta del extracto.');setAccount(name);setDraft(next);setRows(buildReview(statement,name,next));setError('');setStep('review');}catch(e){fail(e);}}
 function update(i:number,p:Partial<ReviewRow>){setRows(rows.map((r,k)=>k===i?{...r,...p}:r));}
 function finish(){try{const out=applyReview(rows,draft,account);onSave(out.data);setResult(`${out.created} movimientos importados${out.paired?` · ${out.paired} transferencias emparejadas`:''}.`);setStep('done');}catch(e){fail(e);}}
 const chosen=rows.filter(r=>r.include&&r.status!=='duplicate'),total=(t:ReviewRow['type'])=>chosen.filter(r=>r.type===t).reduce((n,r)=>n+Math.abs(r.row.amountCents),0);
 const others=Array.from(new Set([...names,...assets.filter(a=>a.type==='Inversión').map(a=>a.name),EXTERNAL])).filter(n=>n!==account);
 return <div className="settings import-flow"><header className="set-page-head"><button className="icon-button" aria-label="Volver" onClick={onBack}><ArrowLeft/></button><h1>Importar movimientos</h1></header>
  {error&&<p className="error" role="alert">{error}</p>}
  {step==='owner'&&<section className="set-card import-pad"><h2>¿A nombre de quién están tus cuentas?</h2><p>Si una transferencia va de una cuenta tuya a otra, no contará como gasto ni como ingreso: solo moverá el saldo.</p><form onSubmit={e=>{e.preventDefault();const v=owner.trim().replace(/\s+/g,' ');if(v.split(' ').length<2)return setError('Escribe nombre y apellidos como aparecen en el banco.');const next={...data,profile:{...data.profile,ownerName:v}};try{onSave(next);setDraft(next);setError('');setStep('file');}catch(err){fail(err);}}}><label>Titular de las cuentas<input value={owner} maxLength={200} onChange={e=>setOwner(e.target.value)} placeholder="Nombre y apellidos"/></label><button className="primary wide">Continuar</button></form></section>}
  {step==='file'&&<section className="set-card import-pad"><h2>Elige tu extracto</h2><p>CSV de cualquier banco (Trade Republic se reconoce solo) o PDF de N26 y BBVA. El archivo se lee en este dispositivo y no se envía a ningún sitio.</p><label className="file-button primary"><Upload size={18}/> {busy?'Leyendo…':'Seleccionar archivo'}<input type="file" accept=".csv,.pdf,text/csv,application/pdf" disabled={busy} onChange={e=>{pick(e.target.files?.[0]);e.target.value='';}}/></label></section>}
  {step==='map'&&<section className="set-card import-pad"><h2>¿Qué es cada columna?</h2>{(['date','description','amount'] as const).map(k=><label key={k}>{k==='date'?'Fecha':k==='description'?'Concepto':'Importe (negativo = gasto)'}<select value={mapping[k]} onChange={e=>setMapping({...mapping,[k]:Number(e.target.value)})}><option value={-1}>Elige una columna</option>{csv[0].map((h,i)=><option key={i} value={i}>{h||`Columna ${i+1}`} · {csv[1]?.[i]??''}</option>)}</select></label>)}<label>Nombre del banco<input value={csvBank} maxLength={100} onChange={e=>setCsvBank(e.target.value)}/></label><button className="primary wide" onClick={()=>{try{chooseStatement(parseGenericCsv(csv,mapping,csvBank.trim()||'Mi banco'));setError('');}catch(e){fail(e);}}}>Continuar</button></section>}
  {step==='account'&&statement&&<section className="set-card import-pad"><h2>{statement.bankName} · {statement.rows.length} movimientos</h2><label>¿De qué cuenta es este extracto?<select value={account} onChange={e=>setAccount(e.target.value)}>{names.map(n=><option key={n} value={n}>{n}</option>)}<option value="__new">Crear cuenta «{statement.bankName}»</option></select></label>{needsOpening&&<><p className="hint">{account==='__new'?'Indica el saldo que tenía la cuenta':'Esta cuenta aún no tiene saldo inicial. Si lo indicas, se actualizará sola'}{statement.opening?' (lo hemos leído del extracto)':''}. Es el saldo antes de los movimientos de ese día.</p><div className="import-two"><label>Saldo inicial (€)<input inputMode="decimal" value={opening.value} onChange={e=>setOpening({...opening,value:e.target.value})} placeholder="0,00"/></label><label>Fecha<input type="date" value={opening.date} onChange={e=>setOpening({...opening,date:e.target.value})}/></label></div></>}<button className="primary wide" onClick={toReview}>Revisar movimientos</button></section>}
  {step==='review'&&<><section className="set-card import-pad import-summary"><div><small>GASTOS</small><strong>{money(total('expense'))}</strong></div><div><small>INGRESOS</small><strong className="income">{money(total('income'))}</strong></div><div><small>TRANSFERENCIAS</small><strong>{chosen.filter(r=>r.type==='transfer').length}</strong></div></section>
   <ul className="import-list">{rows.map((r,i)=>{const out=r.row.amountCents<0;return <li key={r.row.externalId} className={`import-row${r.include?'':' off'}`}><input type="checkbox" aria-label={`Incluir ${r.merchant}`} checked={r.include} disabled={r.status==='duplicate'} onChange={e=>update(i,{include:e.target.checked})}/><div className="import-main"><strong>{r.merchant}</strong><small>{new Date(r.row.date+'T12:00:00').toLocaleDateString('es-ES',{day:'numeric',month:'short',year:'numeric'})} · <span className={`import-chip ${r.status}`}>{STATUS[r.status]}</span></small>{r.status!=='duplicate'&&r.status!=='paired'&&<div className="import-controls"><select aria-label={`Tipo de ${r.merchant}`} value={r.type} onChange={e=>{const type=e.target.value as ReviewRow['type'];update(i,{type,other:type==='transfer'?r.other||EXTERNAL:r.other});}}><option value={out?'expense':'income'}>{out?'Gasto':'Ingreso'}</option><option value="transfer">Transferencia entre mis cuentas</option></select>{r.type==='transfer'?<select aria-label={`Otra cuenta de ${r.merchant}`} value={r.other} onChange={e=>update(i,{other:e.target.value})}>{Array.from(new Set([...others,r.other])).map(n=><option key={n} value={n}>{out?'→ ':'← '}{n}</option>)}</select>:<select aria-label={`Categoría de ${r.merchant}`} value={r.category} onChange={e=>update(i,{category:e.target.value})}>{Array.from(new Set([...(out?data.categories.map(c=>c.name):['Nómina','Intereses','Venta','Otros']),r.category])).map(c=><option key={c}>{c}</option>)}</select>}</div>}</div><strong className={r.type==='income'?'income':''}>{r.type==='transfer'?'':out?'−':'+'}{money(Math.abs(r.row.amountCents))}</strong></li>;})}</ul>
   <button className="primary wide import-go" disabled={!chosen.length} onClick={finish}>Importar {chosen.length} movimientos</button></>}
  {step==='done'&&<section className="set-card import-pad import-done"><span className="set-icon accent"><Check/></span><h2>Listo</h2><p>{result}</p><button className="primary wide" onClick={onBack}>Volver a Ajustes</button></section>}
 </div>;
}
