import {useEffect,useState} from 'react';
import {ArrowLeft,Zap,RefreshCw,KeyRound,Copy} from 'lucide-react';
import {download,type Transaction} from './domain';
type ShortcutCloud={createToken:()=>Promise<string>;hasToken:()=>Promise<boolean>;fetchShortcut:()=>Promise<Transaction[]>};
export default function Shortcut({onBack,onSync,cloud}:{onBack:()=>void;onSync:(items:Transaction[])=>number;cloud?:ShortcutCloud}){
 const [configured,setConfigured]=useState<boolean|null>(null),[token,setToken]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const [importe,setImporte]=useState('2,50'),[comercio,setComercio]=useState('Comercio de prueba'),[banco,setBanco]=useState('Banco de prueba'),[eventId,setEventId]=useState<string>(()=>crypto.randomUUID());
 const endpoint=`${location.origin}/api/shortcut`;
 useEffect(()=>{cloud?.hasToken().then(setConfigured).catch(()=>setConfigured(false));},[cloud]);
 async function run(action:()=>Promise<void>){setBusy(true);setMessage('');try{await action();}catch(e){setMessage((e as Error).message||'Algo ha fallado.');}finally{setBusy(false);}}
 const sync=async()=>{if(!cloud)return;const added=onSync(await cloud.fetchShortcut());setMessage(added?`${added} gastos nuevos del atajo añadidos.`:'No hay gastos nuevos del atajo.');};
 const copy=(value:string)=>navigator.clipboard?.writeText(value).then(()=>setMessage('Copiado.')).catch(()=>setMessage('No se ha podido copiar; selecciónalo y cópialo a mano.'));
 const template={importe:'[Variable Importe]',comercio:'[Variable Comercio]',tarjeta:'[Variable Tarjeta o pase]',banco:'[Banco fijo]',fecha:'[Fecha yyyy-MM-dd]',idEvento:'[UUID estable por evento]'};
 return <><button className="back" onClick={onBack}><ArrowLeft size={20}/> Ajustes</button><div className="page-heading"><span className="eyebrow">AUTOMATIZACIONES</span><h1>Tu atajo, tus cuentas.</h1><p>Importe, comercio y banco. Cada dato en su sitio.</p></div>
 <section className="purple-panel"><Zap size={28}/><h2>Apple Pay → misGastos</h2><div className="variable-chips"><span>Importe</span><span>Comercio</span><span>Banco</span></div><p>Cada pago con Apple Pay llega a tu cuenta con tu token personal. Nadie más puede ver tus gastos.</p></section>
 {!cloud?<section className="card"><p>Inicia sesión para configurar tu atajo.</p></section>:<>
 <section className="card"><div className="section-title"><h2>Tu token personal</h2><span className={'status '+(configured?'online':'')}>{configured===null?'Comprobando…':configured?'Configurado':'Sin configurar'}</span></div>
  <p>El token identifica tus gastos. Se muestra solo una vez: cópialo en tu atajo. Si generas uno nuevo, el anterior deja de funcionar.</p>
  {token&&<><label>Token (cópialo ahora)<input readOnly value={token} onFocus={e=>e.target.select()}/></label><button className="secondary" onClick={()=>copy(token)}><Copy size={18}/> Copiar token</button></>}
  <label>URL del receptor<input readOnly value={endpoint} onFocus={e=>e.target.select()}/></label>
  <div className="button-row"><button className="primary" disabled={busy} onClick={()=>run(async()=>{if(configured&&!confirm('El token anterior dejará de funcionar y tendrás que cambiarlo en tu atajo. ¿Generar uno nuevo?'))return;setToken(await cloud.createToken());setConfigured(true);setMessage('Token generado. Cópialo en tu atajo.');})}><KeyRound size={18}/> {configured?'Generar un token nuevo':'Generar mi token'}</button><button className="secondary" disabled={busy} onClick={()=>run(sync)}><RefreshCw size={18}/> Traer gastos del atajo</button></div>
  {message&&<p className="notice" role="status">{message}</p>}</section>
 <section className="card"><h2>Prueba con datos inventados</h2><p>Envía un gasto de prueba con el token que acabas de generar. Repetir el mismo ID no lo duplica. No hace ningún pago.</p><div className="form-grid"><label>Importe<input inputMode="decimal" value={importe} onChange={e=>setImporte(e.target.value)}/></label><label>Comercio<input value={comercio} onChange={e=>setComercio(e.target.value)}/></label><label>Banco explícito<input value={banco} onChange={e=>setBanco(e.target.value)}/></label><label>ID del evento<input value={eventId} onChange={e=>setEventId(e.target.value)}/></label></div>
  <div className="button-row"><button className="primary" disabled={busy||!token} onClick={()=>run(async()=>{const r=await fetch('/api/shortcut',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({importe,comercio,banco,idEvento:eventId})});let body:{message?:string;duplicate?:boolean}={};try{body=await r.json();}catch{}if(!r.ok)throw Error(body.message||`Error ${r.status}`);await sync();setMessage(body.duplicate?'Evento ya recibido: no se ha duplicado.':'Prueba recibida y añadida a tus movimientos.');})}>Enviar prueba</button><button className="secondary" onClick={()=>setEventId(crypto.randomUUID())}>Nuevo ID</button></div>{!token&&<p className="hint">Genera un token para poder enviar la prueba.</p>}</section>
 </>}
 <section className="card"><h2>Configurar en Atajos</h2><ol className="guide"><li>Crea una automatización de Cartera en Atajos y selecciona las tarjetas que utilizarás.</li><li>Añade «Obtener contenido de URL» con la URL del receptor de arriba.</li><li>Método POST y cuerpo JSON. Vincula <b>importe</b> a «Importe» y <b>comercio</b> a «Comercio» de la transacción.</li><li>Añade <b>banco</b> como texto fijo para esa tarjeta, o <b>tarjeta</b> vinculada a «Tarjeta o pase».</li><li>Añade <b>idEvento</b>: un UUID nuevo por evento. Fecha opcional con formato yyyy-MM-dd.</li><li>Añade la cabecera <b>Authorization</b>: <code>Bearer</code> seguido de tu token.</li></ol><button className="secondary" onClick={()=>download('misGastos-plantilla-atajo.json',{method:'POST',url:endpoint,headers:{Authorization:'Bearer [TU TOKEN]'},body:template})}>Descargar plantilla JSON sin credenciales</button></section></>;
}
