import {useState,useEffect,useRef} from 'react';
import {X,ChevronLeft,ArrowUpRight,ArrowDownLeft,Wallet} from 'lucide-react';
import {type Transaction,categories,parseMoney,today,validDate,money} from './domain';
import {type Asset,assetValue} from './assets';
export default function TransactionModal({accounts,assets=[],onClose,onSave,initial}:{initial?:Transaction;accounts:string[];assets?:Asset[];onClose:()=>void;onSave:(t:Transaction)=>void}){
 const storedAssets=assets.length?assets: (()=>{try{const raw=localStorage.getItem('misgastos.local.v1');const parsed=raw?JSON.parse(raw):null;return Array.isArray(parsed?.assets)?parsed.assets as Asset[]:[];}catch{return [];}})();
 const available=storedAssets.filter(a=>['Cuenta','Efectivo','Ahorro'].includes(a.type));
 const choices=available.length?available:accounts.map((name,i)=>({id:`legacy-${i}`,name,color:'#5b21b6',bank:'',type:'Cuenta' as const,notes:'',valuations:[]}));
 const [step,setStep]=useState(initial?2:0),[type,setType]=useState<'expense'|'income'>(initial?.type??'expense'),[date,setDate]=useState(initial?.date??today()),[category,setCategory]=useState(initial?.category??''),[amount,setAmount]=useState(initial?String(initial.amountCents/100):''),[merchant,setMerchant]=useState(initial?.merchant??''),[bank,setBank]=useState(initial?.bank??choices[0]?.name??''),[error,setError]=useState('');const dialog=useRef<HTMLDialogElement>(null);const saved=useRef(false);
 useEffect(()=>{dialog.current?.showModal();},[]);
 const close=()=>{if((amount||merchant||category)&&!confirm('¿Descartar este movimiento sin guardar?'))return;onClose();};
 function save(){try{if(saved.current)return;if(!validDate(date))throw Error('Selecciona una fecha válida.');if(!category)throw Error('Selecciona una categoría.');const amountCents=parseMoney(amount);saved.current=true;onSave({...initial,id:initial?.id??crypto.randomUUID(),type,date,category,amountCents,merchant:merchant.trim()||category,bank,source:initial?.source??'manual'});}catch(e){saved.current=false;setError((e as Error).message);}}
 return <dialog ref={dialog} className="modal" onCancel={e=>{e.preventDefault();close();}} aria-labelledby="modal-title"><div className="handle"/><div className="modal-top"><button className="icon-button" aria-label="Paso anterior" disabled={step===0} onClick={()=>setStep(step-1)}><ChevronLeft/></button><div className="steps" aria-label={`Paso ${step+1} de 3`}>{[0,1,2].map(n=><span key={n} className={step===n?'selected':''}/>)}</div><button className="icon-button" aria-label="Cerrar formulario" onClick={close}><X/></button></div><div className="segmented"><button className={type==='expense'?'selected':''} onClick={()=>{setType('expense');setCategory('');}}><ArrowUpRight size={18}/> Gasto</button><button className={type==='income'?'selected green':''} onClick={()=>{setType('income');setCategory('');}}><ArrowDownLeft size={18}/> Ingreso</button></div><div className="modal-body">{step===0?<><h2 id="modal-title">¿Cuándo fue?</h2><p>Selecciona la fecha {type==='expense'?'del gasto':'de la entrada'}.</p><label className="date-field">Fecha del movimiento<input type="date" value={date} onChange={e=>setDate(e.target.value)} required/></label><div className="hint">Tus movimientos se guardan en este dispositivo.</div></>:step===1?<><h2 id="modal-title">¿Qué categoría?</h2><p>Cada movimiento, en su sitio.</p><div className="category-list">{(type==='expense'?categories:['Nómina','Venta','Otros']).map((c,i)=><button key={c} className={category===c?'category selected':'category'} onClick={()=>setCategory(c)}><span className="category-dot" style={{background:['#f3e8ff','#e0f2fe','#fce7f3'][i%3]}}><Wallet size={20}/></span>{c}<span className="radio"/></button>)}</div></>:<><h2 id="modal-title" className="sr-only">Importe y cuenta</h2><label className="amount-label">Importe en euros<input autoFocus inputMode="decimal" placeholder="0,00" value={amount} onChange={e=>setAmount(e.target.value)} aria-label="Importe en euros"/></label><label>Comercio o concepto<input value={merchant} maxLength={200} onChange={e=>setMerchant(e.target.value)} placeholder="¿En qué has gastado?"/></label><fieldset className="account-picker"><legend>Cuenta</legend>{choices.length?<div className="account-stack">{choices.map(a=><button type="button" key={a.id} className={bank===a.name?'account-choice selected':''} style={{background:a.color}} onClick={()=>setBank(a.name)}><strong>{a.name}</strong><span>{a.bank||a.type}</span><em>{money(assetValue(a))}</em><b>{bank===a.name?'✓':''}</b></button>)}</div>:<p className="hint">Añade una cuenta en Patrimonio para elegirla aquí.</p>}</fieldset></>}{error&&<p role="alert" className="error">{error}</p>}</div><button className="primary wide" disabled={step===0?!validDate(date):step===1?!category:false} onClick={()=>step<2?setStep(step+1):save()}>{step<2?'Siguiente':`Guardar ${type==='expense'?'gasto':'ingreso'}`}</button></dialog>;
}
