// @vitest-environment jsdom
import React from 'react';
import {beforeEach,describe,it,expect,vi} from 'vitest';
import {render,screen,fireEvent,cleanup} from '@testing-library/react';
import type {SupabaseClient} from '@supabase/supabase-js';
import Login from './Login';

const fakeDb=(signInError?:string)=>{const auth={signInWithPassword:vi.fn(async()=>({error:signInError?{message:signInError}:null})),resetPasswordForEmail:vi.fn(async()=>({error:null})),updateUser:vi.fn(async()=>({error:null}))};return {db:{auth} as unknown as SupabaseClient,auth};};
beforeEach(()=>{cleanup();vi.unstubAllGlobals();});
describe('login screen',()=>{
 it('signs in and translates wrong credentials',async()=>{const {db,auth}=fakeDb('Invalid login credentials');render(<Login db={db}/>);fireEvent.change(screen.getByLabelText('Email'),{target:{value:'ana@ejemplo.com'}});fireEvent.change(screen.getByLabelText('Contraseña'),{target:{value:'secreta123'}});fireEvent.click(screen.getByRole('button',{name:'Entrar'}));expect(await screen.findByText('Email o contraseña incorrectos.')).toBeTruthy();expect(auth.signInWithPassword).toHaveBeenCalledWith({email:'ana@ejemplo.com',password:'secreta123'});});
 it('creates an account with the invite code and then signs in',async()=>{const {db,auth}=fakeDb();const fetchMock=vi.fn(async()=>new Response(JSON.stringify({ok:true}),{status:201}));vi.stubGlobal('fetch',fetchMock);render(<Login db={db}/>);fireEvent.click(screen.getByRole('button',{name:'Crear cuenta'}));fireEvent.change(screen.getByLabelText('Email'),{target:{value:'ana@ejemplo.com'}});fireEvent.change(screen.getByLabelText('Contraseña'),{target:{value:'secreta123'}});fireEvent.change(screen.getByLabelText('Código de invitación'),{target:{value:'AMIGOS-2026'}});fireEvent.click(screen.getByRole('button',{name:'Crear cuenta'}));await vi.waitFor(()=>expect(auth.signInWithPassword).toHaveBeenCalled());expect(JSON.parse((fetchMock.mock.calls[0] as unknown as [string,RequestInit])[1].body as string)).toEqual({email:'ana@ejemplo.com',password:'secreta123',code:'AMIGOS-2026'});});
 it('shows the server message when the invite is rejected',async()=>{const {db,auth}=fakeDb();vi.stubGlobal('fetch',vi.fn(async()=>new Response(JSON.stringify({message:'El código de invitación no es válido o ya se ha usado.'}),{status:403})));render(<Login db={db}/>);fireEvent.click(screen.getByRole('button',{name:'Crear cuenta'}));fireEvent.change(screen.getByLabelText('Email'),{target:{value:'ana@ejemplo.com'}});fireEvent.change(screen.getByLabelText('Contraseña'),{target:{value:'secreta123'}});fireEvent.change(screen.getByLabelText('Código de invitación'),{target:{value:'MALO'}});fireEvent.click(screen.getByRole('button',{name:'Crear cuenta'}));expect(await screen.findByText(/no es válido/)).toBeTruthy();expect(auth.signInWithPassword).not.toHaveBeenCalled();});
 it('sends the password reset email and sets a new password in recovery',async()=>{const {db,auth}=fakeDb();const view=render(<Login db={db}/>);fireEvent.click(screen.getByRole('button',{name:/olvidado/}));fireEvent.change(screen.getByLabelText('Email'),{target:{value:'ana@ejemplo.com'}});fireEvent.click(screen.getByRole('button',{name:'Enviar enlace'}));expect(await screen.findByText(/te hemos enviado un enlace/)).toBeTruthy();expect(auth.resetPasswordForEmail).toHaveBeenCalled();view.unmount();const done=vi.fn();render(<Login db={db} recovery onRecovered={done}/>);fireEvent.change(screen.getByLabelText('Nueva contraseña'),{target:{value:'nuevaClave1'}});fireEvent.click(screen.getByRole('button',{name:'Guardar contraseña'}));await vi.waitFor(()=>expect(done).toHaveBeenCalled());expect(auth.updateUser).toHaveBeenCalledWith({password:'nuevaClave1'});});
});
