import {useState} from 'react';
import {ArrowLeft,ChevronLeft,ChevronRight,Info,List,Pencil,Plus,Repeat2} from 'lucide-react';
import {money,parseMoney,shiftMonth,type Data} from '../domain';
import {budgetSummary,historicalPlannedSavingsCents,saveMonthPlan,type IncomeItem} from '../budget/model';
import {Sheet,parseNonnegative} from './shared';
import './budget.css';

type Props={data:Data;month:string;onMonth:(month:string)=>void;onSave:(data:Data)=>void;onBack:()=>void;onRecurring:()=>void;onGoals:()=>void};
type Editor='income'|'spend'|'limit'|'savings'|'actual'|null;
const tileMoney=(cents:number)=>new Intl.NumberFormat('es-ES',{maximumFractionDigits:2}).format(cents/100)+'€';
const monthTitle=(month:string)=>{const label=new Date(month+'-01T12:00:00').toLocaleDateString('es-ES',{month:'long'});return label[0].toLocaleUpperCase('es')+label.slice(1)+' '+month.slice(0,4);};
export default function BudgetPage({data,month,onMonth,onSave,onBack,onRecurring,onGoals}:Props){
 const s=budgetSummary(data,month),[editor,setEditor]=useState<Editor>(null),[draft,setDraft]=useState(''),[name,setName]=useState(''),[itemAmount,setItemAmount]=useState(''),[category,setCategory]=useState(data.categories[0]?.name??''),[recurring,setRecurring]=useState(false),[editingItem,setEditingItem]=useState(''),[error,setError]=useState('');
 const open=(kind:Editor)=>{setEditor(kind);setError('');setDraft(kind==='income'?String(s.plan.incomeTotalCents/100):kind==='spend'?String(s.plan.plannedSpendCents/100):kind==='savings'?String(s.plan.unassignedSavingsCents/100):kind==='actual'?String(s.plan.actualSavingsCents/100):'');setName('');setItemAmount('');setCategory(data.categories[0]?.name??'');setRecurring(false);setEditingItem('');};
 const commit=(fn:()=>Data)=>{try{onSave(fn());setEditor(null);setError('');}catch(e){setError((e as Error).message);}};
 const saveManual=()=>commit(()=>saveMonthPlan(data,month,{incomeTotalCents:parseNonnegative(draft),incomeItems:[]}));
 const saveItem=()=>commit(()=>{if(!name.trim())throw Error('Escribe el nombre del ingreso.');const item:IncomeItem={id:editingItem||crypto.randomUUID(),name:name.trim(),amountCents:parseMoney(itemAmount),recurring};return saveMonthPlan(data,month,{incomeItems:editingItem?s.plan.incomeItems.map(existing=>existing.id===editingItem?item:existing):[...s.plan.incomeItems,item]});});
 const removeItem=(id:string)=>commit(()=>saveMonthPlan(data,month,{incomeItems:s.plan.incomeItems.filter(item=>item.id!==id)}));
 const saveLimit=()=>commit(()=>{if(!category)throw Error('Elige una categoría.');return saveMonthPlan(data,month,{categoryLimits:{...s.plan.categoryLimits,[category]:parseNonnegative(draft)}});});
 const limitNames=[...new Set([...data.categories.map(c=>c.name),...Object.keys(s.plan.categoryLimits)])];
 const configured=Object.keys(data.planning.months).sort().reverse();
 return <div className="budget-page">
 <header className="budget-header"><button className="budget-back" onClick={onBack} aria-label="Volver"><ArrowLeft size={24}/></button><h1>Presupuestos</h1></header>
 <div className="budget-month" aria-label="Mes del presupuesto"><button aria-label="Mes anterior" onClick={()=>onMonth(shiftMonth(month,-1))}><ChevronLeft size={25}/></button><strong>{monthTitle(month)}</strong><button aria-label="Mes siguiente" onClick={()=>onMonth(shiftMonth(month,1))}><ChevronRight size={25}/></button></div>
 <h2 className="budget-plan-title">Plan del mes</h2>
 <div className="budget-four">
  <section className="budget-tile"><small>INGRESOS MENSUALES</small><div className="budget-tile-bottom"><strong>{tileMoney(s.plannedIncomeCents)}</strong><button className="budget-tile-action" aria-label="Editar ingresos" onClick={()=>open('income')}><Pencil size={21}/></button></div></section>
  <section className="budget-tile"><small>GASTO PREVISTO</small><div className="budget-tile-bottom"><strong>{tileMoney(s.plannedSpendCents)}</strong><button className="budget-tile-action" aria-label="Editar gasto previsto" onClick={()=>open('spend')}><Pencil size={21}/></button></div></section>
  <section className="budget-tile budget-tile-fixed"><small><Repeat2 size={15}/> FIJOS MENSUALES</small><div className="budget-tile-bottom"><strong>{tileMoney(Math.round(s.fixedExpenseMonthlyCents+s.fixedInvestmentMonthlyCents))}</strong><button className="budget-tile-action" aria-label="Recurrentes y deudas" onClick={onRecurring}><List size={22}/></button></div></section>
  <section className="budget-tile budget-tile-savings"><div className="budget-tile-heading"><small>AHORRO</small><button className="budget-info" aria-label="Información del ahorro" onClick={()=>open('savings')}><Info size={18}/></button></div><div className="budget-tile-bottom"><div><strong>{tileMoney(s.plan.actualSavingsCents)}</strong><p>de {tileMoney(Math.round(s.plannedSavingsCents))} previstos</p></div><button className="budget-tile-action" aria-label="Editar ahorro" onClick={()=>open('savings')}><List size={22}/></button></div></section>
 </div>
 {!data.planning.months[month]&&<p className="budget-note">Plan mostrado desde el último mes configurado. Se guardará para {month} cuando lo edites.</p>}
 <section className="card"><div className="section-title"><h2>Así va el mes</h2><span className="small-pill">Movimientos reales</span></div><div className="budget-pair"><div><small>GASTADO</small><strong>{money(s.actualSpendCents)}</strong></div><div><small>DISPONIBLE DEL PLAN</small><strong>{money(s.availableSpendCents)}</strong></div></div><progress aria-label="Gasto frente al plan" value={Math.min(s.actualSpendCents,s.plannedSpendCents)} max={s.plannedSpendCents||1}/>{s.availableSpendCents<0&&<p className="budget-alert">Te has pasado {money(-s.availableSpendCents)} del gasto previsto.</p>}{s.planBalanceCents<0&&<p className="budget-alert">Plan deficitario por {money(-s.planBalanceCents)}. Revisa ingresos o asignaciones.</p>}{s.plannedIncomeCents===0&&<p className="budget-alert">Aún no has previsto ingresos para este mes.</p>}<p className="hint">El plan no representa dinero disponible en una cuenta. Los importes reales salen solo de movimientos registrados.</p></section>
 <section className="card"><div className="section-title"><h2>Límites por categoría</h2><button className="text-button" onClick={()=>open('limit')}><Plus size={16}/> Añadir límite de categoría</button></div>{!s.categories.length?<p className="budget-empty">Sin límites ni gastos por categoría todavía.</p>:<div className="budget-rows">{s.categories.map(c=><div className="budget-row" key={c.category}><div><strong>{c.category}{c.orphaned?' · categoría eliminada':''}</strong><small>Gastado {money(c.actualCents)} · Límite {money(c.limitCents)}</small></div><strong className={c.remainingCents<0?'budget-negative':''}>{money(c.remainingCents)}</strong><button className="text-button" onClick={()=>{open('limit');setCategory(c.category);setDraft(String(c.limitCents/100));}}>Editar</button></div>)}</div>}</section>
 <section className="card"><h2>Histórico de ahorro</h2><p>El ahorro real se anota manualmente; no se deduce de tus cuentas.</p>{!configured.length?<p className="budget-empty">Aún no hay meses guardados.</p>:<div className="budget-rows">{configured.map(m=><div className="budget-row" key={m}><strong>{m}</strong><span>{historicalPlannedSavingsCents(data,m)===null?'Sin histórico previsto':`Previsto ${money(historicalPlannedSavingsCents(data,m)!)} `}</span><span>Real anotado {money(data.planning.months[m].actualSavingsCents)}</span></div>)}</div>}<p className="budget-actual">Este mes: <strong>{money(s.plan.actualSavingsCents)}</strong></p><button className="text-button" onClick={()=>open('actual')}>Anotar ahorro real</button></section>
 <Sheet title={editor==='income'?'Ingresos previstos':editor==='spend'?'Gasto previsto':editor==='limit'?'Límite de categoría':editor==='savings'?'Ahorro sin objetivo':'Ahorro real'} open={editor!==null} onClose={()=>setEditor(null)} error={error}>
  {editor==='income'&&<><p>Usa un total manual o añade partidas. Las partidas sustituyen al total en el cálculo.</p><label>Ingreso mensual previsto<input inputMode="decimal" value={draft} onChange={e=>setDraft(e.target.value)}/></label><button className="primary" onClick={saveManual}>Guardar ingresos</button><div className="budget-divider"/><h3>Partidas</h3>{s.plan.incomeItems.map(item=><div className="budget-row" key={item.id}><span>{item.name} · {money(item.amountCents)} {item.recurring?'· recurrente':''}</span><div className="budget-actions"><button className="text-button" aria-label={`Editar partida ${item.name}`} onClick={()=>{setEditingItem(item.id);setName(item.name);setItemAmount(String(item.amountCents/100));setRecurring(item.recurring);}}>Editar</button><button className="text-button danger" aria-label={`Quitar ${item.name}`} onClick={()=>removeItem(item.id)}>Quitar</button></div></div>)}<label>Nombre de la partida<input maxLength={200} value={name} onChange={e=>setName(e.target.value)}/></label><label>Importe de la partida<input inputMode="decimal" value={itemAmount} onChange={e=>setItemAmount(e.target.value)}/></label><label className="budget-check"><input type="checkbox" checked={recurring} onChange={e=>setRecurring(e.target.checked)}/> Repetir en el plan de los próximos meses</label><button className="secondary" onClick={saveItem}>{editingItem?'Guardar partida':'Añadir partida'}</button></>}
  {editor==='spend'&&<><label>Gasto mensual previsto<input inputMode="decimal" value={draft} onChange={e=>setDraft(e.target.value)}/></label><button className="primary" onClick={()=>commit(()=>saveMonthPlan(data,month,{plannedSpendCents:parseNonnegative(draft)}))}>Guardar gasto previsto</button></>}
  {editor==='limit'&&<><label>Categoría del límite<select value={category} onChange={e=>setCategory(e.target.value)}>{limitNames.map(c=><option key={c}>{c}</option>)}</select></label><label>Límite mensual<input inputMode="decimal" value={draft} onChange={e=>setDraft(e.target.value)}/></label><button className="primary" onClick={saveLimit}>Guardar límite</button></>}
  {editor==='savings'&&<><p>El ahorro previsto suma los objetivos y la cantidad sin objetivo. El ahorro real se anota por separado.</p><label>Ahorro mensual sin objetivo<input inputMode="decimal" value={draft} onChange={e=>setDraft(e.target.value)}/></label><button className="primary" onClick={()=>commit(()=>saveMonthPlan(data,month,{unassignedSavingsCents:parseNonnegative(draft)}))}>Guardar ahorro</button><button className="secondary" onClick={()=>{setEditor(null);onGoals();}}>Objetivos</button><p className="hint">Es una asignación del plan, no una transferencia.</p></>}
  {editor==='actual'&&<><label>Ahorro real del mes<input inputMode="decimal" value={draft} onChange={e=>setDraft(e.target.value)}/></label><button className="primary" onClick={()=>commit(()=>saveMonthPlan(data,month,{actualSavingsCents:parseNonnegative(draft)}))}>Guardar ahorro real</button></>}
 </Sheet></div>;
}
