import {useState} from 'react';
import {ArrowLeft,ChevronRight,Plus} from 'lucide-react';
import {money,parseMoney,type Data} from '../domain';
import {MonthSelector} from '../components';
import {budgetSummary,historicalPlannedSavingsCents,saveMonthPlan,type IncomeItem} from '../budget/model';
import {Sheet,parseNonnegative} from './shared';
import './budget.css';

type Props={data:Data;month:string;onMonth:(month:string)=>void;onSave:(data:Data)=>void;onBack:()=>void;onRecurring:()=>void;onGoals:()=>void};
type Editor='income'|'spend'|'limit'|'savings'|'actual'|null;
export default function BudgetPage({data,month,onMonth,onSave,onBack,onRecurring,onGoals}:Props){
 const s=budgetSummary(data,month),[editor,setEditor]=useState<Editor>(null),[draft,setDraft]=useState(''),[name,setName]=useState(''),[itemAmount,setItemAmount]=useState(''),[category,setCategory]=useState(data.categories[0]?.name??''),[recurring,setRecurring]=useState(false),[editingItem,setEditingItem]=useState(''),[error,setError]=useState('');
 const open=(kind:Editor)=>{setEditor(kind);setError('');setDraft(kind==='income'?String(s.plan.incomeTotalCents/100):kind==='spend'?String(s.plan.plannedSpendCents/100):kind==='savings'?String(s.plan.unassignedSavingsCents/100):kind==='actual'?String(s.plan.actualSavingsCents/100):'');setName('');setItemAmount('');setCategory(data.categories[0]?.name??'');setRecurring(false);setEditingItem('');};
 const commit=(fn:()=>Data)=>{try{onSave(fn());setEditor(null);setError('');}catch(e){setError((e as Error).message);}};
 const saveManual=()=>commit(()=>saveMonthPlan(data,month,{incomeTotalCents:parseNonnegative(draft),incomeItems:[]}));
 const saveItem=()=>commit(()=>{if(!name.trim())throw Error('Escribe el nombre del ingreso.');const item:IncomeItem={id:editingItem||crypto.randomUUID(),name:name.trim(),amountCents:parseMoney(itemAmount),recurring};return saveMonthPlan(data,month,{incomeItems:editingItem?s.plan.incomeItems.map(existing=>existing.id===editingItem?item:existing):[...s.plan.incomeItems,item]});});
 const removeItem=(id:string)=>commit(()=>saveMonthPlan(data,month,{incomeItems:s.plan.incomeItems.filter(item=>item.id!==id)}));
 const saveLimit=()=>commit(()=>{if(!category)throw Error('Elige una categoría.');return saveMonthPlan(data,month,{categoryLimits:{...s.plan.categoryLimits,[category]:parseNonnegative(draft)}});});
 const limitNames=[...new Set([...data.categories.map(c=>c.name),...Object.keys(s.plan.categoryLimits)])];
 const configured=Object.keys(data.planning.months).sort().reverse();
 return <div className="budget-page"><button className="back" onClick={onBack}><ArrowLeft size={20}/> Volver</button><div className="page-heading"><span className="eyebrow">TU PLAN MENSUAL</span><h1>Presupuestos.</h1><p>Organiza lo previsto y compáralo con tus movimientos reales.</p></div><MonthSelector month={month} onChange={onMonth}/>{!data.planning.months[month]&&<p className="budget-note">Plan mostrado desde el último mes configurado. Se guardará para {month} cuando lo edites.</p>}
 <div className="budget-four">
  <section className="card budget-tile"><small>INGRESOS PREVISTOS</small><strong>{money(s.plannedIncomeCents)}</strong><p>{s.plan.incomeItems.length?`${s.plan.incomeItems.length} partidas`:'Total manual del mes'}</p><button className="text-button" onClick={()=>open('income')}>Editar ingresos <ChevronRight size={16}/></button></section>
  <section className="card budget-tile"><small>GASTO PREVISTO</small><strong>{money(s.plannedSpendCents)}</strong><p>Disponible para gastar: {money(s.availableSpendCents)}</p><button className="text-button" onClick={()=>open('spend')}>Editar gasto previsto <ChevronRight size={16}/></button></section>
  <section className="card budget-tile"><small>FIJOS MENSUALIZADOS</small><strong>{money(Math.round(s.fixedExpenseMonthlyCents+s.fixedInvestmentMonthlyCents))}</strong><p>Gastos {money(Math.round(s.fixedExpenseMonthlyCents))} · Inversión {money(Math.round(s.fixedInvestmentMonthlyCents))}</p><button className="text-button" onClick={onRecurring}>Recurrentes y deudas <ChevronRight size={16}/></button></section>
  <section className="card budget-tile"><small>AHORRO PREVISTO</small><strong>{money(Math.round(s.plannedSavingsCents))}</strong><p>Objetivos {money(Math.round(s.goalQuotaCents))} · Sin objetivo {money(s.plan.unassignedSavingsCents)}</p><div className="budget-actions"><button className="text-button" onClick={()=>open('savings')}>Editar ahorro</button><button className="text-button" onClick={onGoals}>Objetivos <ChevronRight size={16}/></button></div></section>
 </div>
 <section className="card"><div className="section-title"><h2>Así va el mes</h2><span className="small-pill">Movimientos reales</span></div><div className="budget-pair"><div><small>GASTADO</small><strong>{money(s.actualSpendCents)}</strong></div><div><small>DISPONIBLE DEL PLAN</small><strong>{money(s.availableSpendCents)}</strong></div></div><progress aria-label="Gasto frente al plan" value={Math.min(s.actualSpendCents,s.plannedSpendCents)} max={s.plannedSpendCents||1}/>{s.availableSpendCents<0&&<p className="budget-alert">Te has pasado {money(-s.availableSpendCents)} del gasto previsto.</p>}{s.planBalanceCents<0&&<p className="budget-alert">Plan deficitario por {money(-s.planBalanceCents)}. Revisa ingresos o asignaciones.</p>}{s.plannedIncomeCents===0&&<p className="budget-alert">Aún no has previsto ingresos para este mes.</p>}<p className="hint">El plan no representa dinero disponible en una cuenta. Los importes reales salen solo de movimientos registrados.</p></section>
 <section className="card"><div className="section-title"><h2>Límites por categoría</h2><button className="text-button" onClick={()=>open('limit')}><Plus size={16}/> Añadir límite de categoría</button></div>{!s.categories.length?<p className="budget-empty">Sin límites ni gastos por categoría todavía.</p>:<div className="budget-rows">{s.categories.map(c=><div className="budget-row" key={c.category}><div><strong>{c.category}{c.orphaned?' · categoría eliminada':''}</strong><small>Gastado {money(c.actualCents)} · Límite {money(c.limitCents)}</small></div><strong className={c.remainingCents<0?'budget-negative':''}>{money(c.remainingCents)}</strong><button className="text-button" onClick={()=>{open('limit');setCategory(c.category);setDraft(String(c.limitCents/100));}}>Editar</button></div>)}</div>}</section>
 <section className="card"><h2>Histórico de ahorro</h2><p>El ahorro real se anota manualmente; no se deduce de tus cuentas.</p>{!configured.length?<p className="budget-empty">Aún no hay meses guardados.</p>:<div className="budget-rows">{configured.map(m=><div className="budget-row" key={m}><strong>{m}</strong><span>{historicalPlannedSavingsCents(data,m)===null?'Sin histórico previsto':`Previsto ${money(historicalPlannedSavingsCents(data,m)!)} `}</span><span>Real anotado {money(data.planning.months[m].actualSavingsCents)}</span></div>)}</div>}<p className="budget-actual">Este mes: <strong>{money(s.plan.actualSavingsCents)}</strong></p><button className="text-button" onClick={()=>open('actual')}>Anotar ahorro real</button></section>
 <Sheet title={editor==='income'?'Ingresos previstos':editor==='spend'?'Gasto previsto':editor==='limit'?'Límite de categoría':editor==='savings'?'Ahorro sin objetivo':'Ahorro real'} open={editor!==null} onClose={()=>setEditor(null)} error={error}>
  {editor==='income'&&<><p>Usa un total manual o añade partidas. Las partidas sustituyen al total en el cálculo.</p><label>Ingreso mensual previsto<input inputMode="decimal" value={draft} onChange={e=>setDraft(e.target.value)}/></label><button className="primary" onClick={saveManual}>Guardar ingresos</button><div className="budget-divider"/><h3>Partidas</h3>{s.plan.incomeItems.map(item=><div className="budget-row" key={item.id}><span>{item.name} · {money(item.amountCents)} {item.recurring?'· recurrente':''}</span><div className="budget-actions"><button className="text-button" aria-label={`Editar partida ${item.name}`} onClick={()=>{setEditingItem(item.id);setName(item.name);setItemAmount(String(item.amountCents/100));setRecurring(item.recurring);}}>Editar</button><button className="text-button danger" aria-label={`Quitar ${item.name}`} onClick={()=>removeItem(item.id)}>Quitar</button></div></div>)}<label>Nombre de la partida<input maxLength={200} value={name} onChange={e=>setName(e.target.value)}/></label><label>Importe de la partida<input inputMode="decimal" value={itemAmount} onChange={e=>setItemAmount(e.target.value)}/></label><label className="budget-check"><input type="checkbox" checked={recurring} onChange={e=>setRecurring(e.target.checked)}/> Repetir en el plan de los próximos meses</label><button className="secondary" onClick={saveItem}>{editingItem?'Guardar partida':'Añadir partida'}</button></>}
  {editor==='spend'&&<><label>Gasto mensual previsto<input inputMode="decimal" value={draft} onChange={e=>setDraft(e.target.value)}/></label><button className="primary" onClick={()=>commit(()=>saveMonthPlan(data,month,{plannedSpendCents:parseNonnegative(draft)}))}>Guardar gasto previsto</button></>}
  {editor==='limit'&&<><label>Categoría del límite<select value={category} onChange={e=>setCategory(e.target.value)}>{limitNames.map(c=><option key={c}>{c}</option>)}</select></label><label>Límite mensual<input inputMode="decimal" value={draft} onChange={e=>setDraft(e.target.value)}/></label><button className="primary" onClick={saveLimit}>Guardar límite</button></>}
  {editor==='savings'&&<><label>Ahorro mensual sin objetivo<input inputMode="decimal" value={draft} onChange={e=>setDraft(e.target.value)}/></label><button className="primary" onClick={()=>commit(()=>saveMonthPlan(data,month,{unassignedSavingsCents:parseNonnegative(draft)}))}>Guardar ahorro</button><p className="hint">Es una asignación del plan, no una transferencia.</p></>}
  {editor==='actual'&&<><label>Ahorro real del mes<input inputMode="decimal" value={draft} onChange={e=>setDraft(e.target.value)}/></label><button className="primary" onClick={()=>commit(()=>saveMonthPlan(data,month,{actualSavingsCents:parseNonnegative(draft)}))}>Guardar ahorro real</button></>}
 </Sheet></div>;
}
