import {useState} from 'react';
import {ArrowLeft,Plus} from 'lucide-react';
import {money,parseMoney,today,validDate,type Data} from '../domain';
import {debtBalance,monthlyRecurring,validatePlanning,type Recurring,type Debt} from '../budget/model';
import {Sheet} from './shared';
import './budget.css';
type Props={data:Data;onSave:(data:Data)=>void;onBack:()=>void};
type Mode='recurring'|'debt'|'payment'|null;
export default function RecurringDebtsPage({data,onSave,onBack}:Props){
 const [tab,setTab]=useState<'recurring'|'debts'>('recurring'),[mode,setMode]=useState<Mode>(null),[error,setError]=useState(''),[name,setName]=useState(''),[amount,setAmount]=useState(''),[cadence,setCadence]=useState<Recurring['cadence']>('monthly'),[date,setDate]=useState(today()),[category,setCategory]=useState(data.categories[0]?.name??'Otros'),[kind,setKind]=useState<Recurring['kind']>('expense'),[direction,setDirection]=useState<Debt['direction']>('iOwe'),[reminder,setReminder]=useState(false),[target,setTarget]=useState(''),[filter,setFilter]=useState('all');
 const close=()=>{setMode(null);setError('');};
 const open=(next:Mode,id='')=>{setMode(next);setTarget(id);setError('');setName('');setAmount('');setDate(next==='recurring'?today():'');setCadence('monthly');setCategory(data.categories[0]?.name??'Otros');setKind('expense');setDirection('iOwe');setReminder(false);};
 const commit=(fn:()=>Data)=>{try{const next=fn();validatePlanning(next.planning);onSave(next);close();}catch(e){setError((e as Error).message);}};
 const saveRecurring=()=>commit(()=>{if(!name.trim())throw Error('Escribe el nombre.');if(!validDate(date))throw Error('Fecha no válida.');const item:Recurring={id:crypto.randomUUID(),name:name.trim(),amountCents:parseMoney(amount),cadence,nextDate:date,category,kind,status:'active'};return {...data,planning:{...data.planning,recurrents:[...data.planning.recurrents,item]}};});
 const saveDebt=()=>commit(()=>{if(!name.trim())throw Error('Escribe la persona o entidad.');if(date&&!validDate(date))throw Error('Fecha no válida.');const item:Debt={id:crypto.randomUUID(),direction,counterparty:name.trim(),originalCents:parseMoney(amount),paidCents:0,...(date?{dueDate:date}:{}),reminder};return {...data,planning:{...data.planning,debts:[...data.planning.debts,item]}};});
 const changeStatus=(id:string,status:Recurring['status'])=>commit(()=>({...data,planning:{...data.planning,recurrents:data.planning.recurrents.map(r=>r.id===id?{...r,status}:r)}}));
 const pay=()=>commit(()=>{const cents=parseMoney(amount),debt=data.planning.debts.find(d=>d.id===target);if(!debt||cents>debtBalance(debt))throw Error('El pago supera el saldo pendiente.');return {...data,planning:{...data.planning,debts:data.planning.debts.map(d=>d.id===target?{...d,paidCents:d.paidCents+cents}:d)}};});
 const monthly=monthlyRecurring(data.planning.recurrents);
 return <div className="budget-page"><button className="back" onClick={onBack}><ArrowLeft size={20}/> Volver a presupuestos</button><div className="page-heading"><span className="eyebrow">COMPROMISOS Y PENDIENTES</span><h1>Recurrentes y deudas.</h1><p>Planifica cuotas y registra pagos sin alterar movimientos bancarios.</p></div><div role="tablist" className="budget-tabs"><button role="tab" aria-selected={tab==='recurring'} onClick={()=>setTab('recurring')}>Recurrentes</button><button role="tab" aria-selected={tab==='debts'} onClick={()=>setTab('debts')}>Deudas</button></div>
 {tab==='recurring'?<><section className="card"><small>ACTIVOS MENSUALIZADOS</small><h2>{money(Math.round(monthly))} / mes</h2><p>Los importes trimestrales y anuales se reparten entre 3 y 12 meses para la previsión. No se crea ningún gasto real.</p><button className="primary" onClick={()=>open('recurring')}><Plus size={17}/> Añadir recurrente</button></section><section className="card"><h2>Recurrentes</h2>{!data.planning.recurrents.length?<p className="budget-empty">Aún no hay pagos o inversiones recurrentes.</p>:data.planning.recurrents.map(r=><div className="budget-row" key={r.id}><div><strong>{r.name}</strong><small>{money(r.amountCents)} · {r.cadence==='monthly'?'mensual':r.cadence==='quarterly'?'trimestral':'anual'} · {r.category} · {r.status==='active'?'Activo':r.status==='paused'?'Pausado':'Cancelado'}</small></div><div className="budget-row-actions">{r.status==='active'&&<button className="text-button" aria-label={`Pausar ${r.name}`} onClick={()=>changeStatus(r.id,'paused')}>Pausar</button>}{r.status==='paused'&&<button className="text-button" aria-label={`Reanudar ${r.name}`} onClick={()=>changeStatus(r.id,'active')}>Reanudar</button>}{r.status!=='cancelled'&&<button className="text-button danger" aria-label={`Cancelar ${r.name}`} onClick={()=>changeStatus(r.id,'cancelled')}>Cancelar</button>}</div></div>)}</section></>:<><section className="card"><div className="section-title"><h2>Deudas</h2><button className="primary" onClick={()=>open('debt')}><Plus size={17}/> Añadir deuda</button></div><label>Filtrar deudas<select aria-label="Filtrar deudas" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Todas</option><option value="iOwe">Yo debo</option><option value="owedToMe">Me deben</option><option value="settled">Saldadas</option></select></label>{!data.planning.debts.length?<p className="budget-empty">Aún no hay deudas.</p>:data.planning.debts.filter(d=>filter==='all'||filter==='settled'&&debtBalance(d)===0||filter===d.direction&&debtBalance(d)>0).map(d=><div className="budget-row" key={d.id}><div><strong>{d.counterparty}</strong><small>{d.direction==='iOwe'?'Yo debo':'Me deben'} · Original {money(d.originalCents)} · {debtBalance(d)===0?'Saldada':d.dueDate?`Vence ${d.dueDate}`:'Sin vencimiento'}</small></div><strong>{money(debtBalance(d))}</strong>{debtBalance(d)>0&&<button className="text-button" aria-label={`Registrar pago de ${d.counterparty}`} onClick={()=>open('payment',d.id)}>Registrar pago</button>}</div>)}</section><p className="hint">Un pago aquí solo actualiza la deuda. Registra el movimiento real por separado. Los recordatorios quedan anotados, sin notificaciones automáticas.</p></>}
 <Sheet open={mode!==null} title={mode==='recurring'?'Nuevo recurrente':mode==='debt'?'Nueva deuda':'Registrar pago'} onClose={close} error={error}>
 {mode==='recurring'&&<><label>Nombre del recurrente<input maxLength={200} value={name} onChange={e=>setName(e.target.value)}/></label><label>Importe del recurrente<input inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>Frecuencia<select value={cadence} onChange={e=>setCadence(e.target.value as Recurring['cadence'])}><option value="monthly">Mensual</option><option value="quarterly">Trimestral</option><option value="yearly">Anual</option></select></label><label>Próxima fecha<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Categoría<select value={category} onChange={e=>setCategory(e.target.value)}>{data.categories.map(c=><option key={c.name}>{c.name}</option>)}</select></label><label>Destino<select value={kind} onChange={e=>setKind(e.target.value as Recurring['kind'])}><option value="expense">Gasto</option><option value="investment">Inversión</option></select></label><button className="primary" onClick={saveRecurring}>Guardar recurrente</button></>}
 {mode==='debt'&&<><label>Dirección<select value={direction} onChange={e=>setDirection(e.target.value as Debt['direction'])}><option value="iOwe">Yo debo</option><option value="owedToMe">Me deben</option></select></label><label>Persona o entidad<input maxLength={200} value={name} onChange={e=>setName(e.target.value)}/></label><label>Importe original<input inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>Vencimiento opcional<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label className="budget-check"><input type="checkbox" checked={reminder} onChange={e=>setReminder(e.target.checked)}/> Marcar para recordatorio manual</label><button className="primary" onClick={saveDebt}>Guardar deuda</button></>}
 {mode==='payment'&&<><p>Este pago reduce el saldo pendiente; no añade un movimiento a tus cuentas.</p><label>Importe del pago<input inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)}/></label><button className="primary" onClick={pay}>Guardar pago</button></>}
 </Sheet></div>;
}
