import {useState} from 'react';
import {ArrowLeft,Plus} from 'lucide-react';
import {money,parseMoney,validDate,type Data} from '../domain';
import {goalQuota,snapshotSavingsMonth,validatePlanning,type SavingsGoal} from '../budget/model';
import {Sheet,parseNonnegative} from './shared';
import './budget.css';
type Props={data:Data;month:string;onSave:(data:Data)=>void;onBack:()=>void};
export default function SavingsGoalsPage({data,month,onSave,onBack}:Props){
 const [open,setOpen]=useState(false),[id,setId]=useState(''),[name,setName]=useState(''),[target,setTarget]=useState(''),[current,setCurrent]=useState('0'),[date,setDate]=useState(''),[error,setError]=useState('');
 const begin=(goal?:SavingsGoal)=>{setOpen(true);setError('');setId(goal?.id??'');setName(goal?.name??'');setTarget(goal?String(goal.targetCents/100):'');setCurrent(goal?String(goal.currentCents/100):'0');setDate(goal?.targetDate??'');};
 const save=()=>{try{if(!name.trim())throw Error('Escribe el nombre del objetivo.');if(!validDate(date))throw Error('Fecha objetivo no válida.');const targetCents=parseMoney(target),currentCents=parseNonnegative(current);if(currentCents>targetCents)throw Error('El saldo actual no puede superar la meta.');const goal:SavingsGoal={id:id||crypto.randomUUID(),name:name.trim(),targetCents,currentCents,targetDate:date};const next={...data,planning:{...data.planning,goals:id?data.planning.goals.map(g=>g.id===id?goal:g):[...data.planning.goals,goal]}};validatePlanning(next.planning);onSave(snapshotSavingsMonth(next,month));setOpen(false);}catch(e){setError((e as Error).message);}};
 const remove=(id:string)=>{try{const next={...data,planning:{...data.planning,goals:data.planning.goals.filter(g=>g.id!==id)}};validatePlanning(next.planning);onSave(snapshotSavingsMonth(next,month));setError('');}catch(e){setError((e as Error).message);}};
 const total=data.planning.goals.reduce((sum,g)=>sum+goalQuota(g,month),0);
 return <div className="budget-page"><button className="back" onClick={onBack}><ArrowLeft size={20}/> Volver a presupuestos</button><div className="page-heading"><span className="eyebrow">UN PASO CADA MES</span><h1>Objetivos de ahorro.</h1><p>Distribuye lo que falta por ahorrar hasta cada fecha objetivo.</p></div>{!open&&error&&<p className="error" role="alert">{error}</p>}<section className="card budget-highlight"><small>CUOTAS DE OBJETIVOS EN {month}</small><h2>{money(Math.round(total))} / mes</h2><p>Esta cantidad forma parte del plan. No representa una transferencia ni el saldo de una cuenta.</p><button className="primary" onClick={()=>begin()}><Plus size={17}/> Añadir objetivo</button></section><section className="card"><h2>Tus objetivos</h2>{!data.planning.goals.length?<p className="budget-empty">Aún no has creado objetivos.</p>:data.planning.goals.map(g=>{const quota=goalQuota(g,month),remaining=Math.max(0,g.targetCents-g.currentCents),[year,m]=month.split('-').map(Number),[endYear,endMonth]=g.targetDate.slice(0,7).split('-').map(Number),months=Math.max(1,(endYear-year)*12+endMonth-m+1);return <div className="budget-goal" key={g.id}><div className="section-title"><h3>{g.name}</h3><span>{money(g.currentCents)} / {money(g.targetCents)}</span></div><progress aria-label={`Progreso de ${g.name}`} value={Math.min(g.currentCents,g.targetCents)} max={g.targetCents}/><p>{remaining?`${money(Math.round(quota))} / mes · ${months} meses · Restan ${money(remaining)}`:'Objetivo completado · cuota mensual 0,00 €'}</p><div className="budget-actions"><button className="text-button" aria-label={`Editar ${g.name}`} onClick={()=>begin(g)}>Editar</button><button className="text-button danger" aria-label={`Eliminar ${g.name}`} onClick={()=>remove(g.id)}>Eliminar</button></div></div>;})}</section><Sheet open={open} title={id?'Editar objetivo':'Nuevo objetivo'} onClose={()=>setOpen(false)} error={error}><label>Nombre del objetivo<input maxLength={200} value={name} onChange={e=>setName(e.target.value)}/></label><label>Meta<input inputMode="decimal" value={target} onChange={e=>setTarget(e.target.value)}/></label><label>Saldo actual<input inputMode="decimal" value={current} onChange={e=>setCurrent(e.target.value)}/></label><label>Fecha objetivo<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><button className="primary" onClick={save}>Guardar objetivo</button></Sheet></div>;
}
